### ISSUE TITLE
[feature request] MathJax support 

### ISSUE THREAD

**Issue by ahmadihamid** [daattali/beautiful-jekyll#195]
Can we have MathJax integrated directly to our theme?

**Comment by daattali** [comment]
I haven't used MathJax myself before so I'm not sure what's involved. Do
you have an example of how to use it?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://attalitech.com

**Comment by ahmadihamid** [comment]
http://docs.mathjax.org/en/latest/index.html

**Comment by ahmadihamid** [comment]
Sorry for the double post but here the example :
https://github.com/mathjax/MathJax/blob/master/test/sample-tex.html

For now I need to write html in my post to render math formula

**Comment by daattali** [comment]
Is your question about how to use mathjax in general, in any html or jekyll
page? Or do you know how to use it in general and are just having trouble
incorporating it with this theme? I'd love to help with the latter but I'd
need to see what you came up with first :)

**Comment by ahmadihamid** [comment]
Ok, I  know how to use it in general but haven't tried to integrate it to this theme, and I hope you could, 
😁

**Comment by daattali** [comment]
I don't have time to go through the full documentation as I'm busy with many projects, but does it simply need to have the javascript file loaded? If so, then you can use the `js` or `ext-js` YAML parameters on the page that you want https://github.com/daattali/beautiful-jekyll#yaml-front-matter-parameters

Simply pass in the URL for the mathjax javascript library

**Comment by ahmadihamid** [comment]
Wow! It just works, thanks.

**Comment by mching** [comment]
If you use a lot of math notation, it might also work to include the script from the [MathJax documentation](http://docs.mathjax.org/en/latest/start.html) in the _includes/head.html file. It's not as elegant or efficient as the solution above but it does make it automatic for every page.

```
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```

**Comment by daattali** [comment]
@mching you can also set `ext-js` YAML parameter in the layout file if you want it to be automatic

**Comment by bakera1** [comment]
Tried the head.html update and worked pretty well for me.

**Comment by ComFreek** [comment]
I spent a few minutes figuring out how to embed math. I hope others will find this useful, enjoy 😄 
<hr>

## 1 Minute Guide to Embed Math

1. Get the CDN link for the MathJax version/variant you desire, e.g. `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML`<br>
  Despite the given version `2.7.5`, this always references the **latest** version! Learn more at [MathJax' getting started guide](https://www.mathjax.org/#gettingstarted).

2. Open `./_config.yml` and add the `ext-js` key to the default YAML values for a post:
```yaml
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      ext-js: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
```

3. Use `\( ... \)` for inline math and `$$ ... $$` for display math in your posts!<br>
    `$ ... $` does **not** work by default; again, learn more at [MathJax' docs on putting mathematics on a web page](https://docs.mathjax.org/en/latest/start.html#putting-mathematics-in-a-web-page).

**Comment by VincentTam** [comment]
@ComFreek Thanks for quick guide.  For the convenience of future readers who are used to LaTeX's single `$` for inline math, here's a [minimal working sample](https://github.com/mathjax/MathJax/blob/39c61f62a9a8196e6caa189ff5771ea31b7f7379/test/sample-tex.html#L10-L15) to get things work.

```html
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
<script type="text/javascript" async
  src="https://example.com/mathjax/MathJax.js?config=TeX-AMS_CHTML">
</script>
</head>
<body>
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
</body>
</html>
```

**Comment by daattali** [comment]
FYI this thread has been linked from the README FAQ section

**Comment by YoniChechik** [comment]
https://stackoverflow.com/a/46765337/4879610

The easiest solution in my opinion

**Comment by jeffreytse** [comment]
Jekyll uses kramdown as a default markdown converter from 2.0+. And It doesn't support the mathjax and so on, I think the below plugin can help you.

> **jekyll-spaceship** - 🚀 A Jekyll plugin to provide powerful supports for table, mathjax, plantuml, youtube, vimeo, dailymotion, etc.

https://github.com/jeffreytse/jekyll-spaceship

Put your math expression within $...$

$ a * b = c ^ b $
$ 2^{\frac{n-1}{3}} $
$ \int\_a^b f(x)\,dx. $

**Comment by daattali** [comment]
Is the mathjax support FAQ solution  from the README no longer working?

**Comment by jeffreytse** [comment]
Hi @daattali, 
It's just another awesome optional solution for **MathJax support** in plugin.
👍 Thanks for your kindly focus and great support.

**Comment by rafisics** [comment]
Hi, I am facing problem activating mathjax in a [post in my github page](https://github.com/rafisics/portfolio/blob/master/_posts/2020-02-28-test-markdown.md). 
I have done the following things. 
- Added the `ext-js` key in the `./_config.yml`:
```
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      ext-js: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-mml-chtml.js"  
```
- Added these lines to `_includes/head.html`:
```
  <!-- for mathjax support -->
  {% if page.usemathjax %}
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
        inlineMath: [['$','$']]
      }
    });
  </script>
  <script type="text/javascript" id="MathJax-script" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-mml-chtml.js"> </script>
  {% endif %}
```
- Added `usemathjax: true` in the YAML front matter in the [markdown file](https://github.com/rafisics/portfolio/blob/master/_posts/2020-02-28-test-markdown.md) of that post.
