### ISSUE TITLE
Optional card layout post archive by categories 

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#238]
It really would be nice to the ability to highlight posts in a given category like this:
![Card collection example](https://i.imgur.com/f0qSxx3.png)

One approach would be:
- adding a new layout called `cards`.
  - based on [material design](https://material.io/guidelines/components/cards.html#) or even better with [bootstrap 4](https://v4-alpha.getbootstrap.com/components/card/#card-layout).
- Adding a new page with this layout option and some additional front matter YAML like this

```yaml
cards :
  - highlight: "awesome posts"
  .....
```

## Card Design
- thin border
- distinct shadow 8-15 px
- Image taken from the post image
- Tite
- Subtitle
- content excerpt with muted style

To adjust some card content we could use front matter in affected posts as well:

```yaml
card:
  - title: "Adjust the title for card usage"
  - subtitle: "Adjust the the subtitle in card layout"
  - image: # Maybe some sizing options
  - excerpt: "This post covers some awesome things like..."
```
