### ISSUE TITLE
Enhancement Request / Suggestion - Social Networks Data

### ISSUE THREAD

**Issue by davchana** [daattali/beautiful-jekyll#277]
Hi, I can not push a PR as I have edited my repository too much; but one thing I was getting bothered was too much repetition of code for social networks in footer (one literal `<li>` per network ):

````html
<li>
  <a href="myemail@foo.bar" title="Email me">
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
    </span>
  </a>
</li>
````

What I did (from help of lot of Stackoverflow & Google & everywhere was:

* created a new directory `_data` & a new file `social.yml` in it to make `_config.yml` less cluterry. Contents of `social.yml` are:

````yaml
# all the social media details used in contact page & #contact section of footer

# SAMPLE
# ==========================================
# site
#   href / url
#   title; to be used as in <a title>
#   user name at site
#   icon name as in Font Awesome
#   Site Name / Text
#   show / use in site?
#   show in footer? above also need to be true
# ==========================================

camera:
    href: "https://myphotowebsite.com/"
    title: "Photos"
    user: "MyPhotoWebsite.com/"
    icon: "camera"
    text: "Photos"
    show: true
    footer: true
instagram:
    href: "https://www.instagram.com/myinsta"
    title: "Instagram"
    user: "myInsta"
    icon: "instagram"
    text: "Instagram"
    show: true
    footer: true
# .. & such
````

& then in footer.html:

````yaml
<ul>
  {% for item in site.data.social %}
    {% if item[1].show %}
      <li>
        <a href="{{ item[1].href }}" target="_blank" class="contact_list" title="{{ item[1].title }} - {{ item[1].user }}">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-{{ item[1].icon }} fa-stack-1x fa-inverse"></i>
          </span> {{ item[1].text }} - {{ item[1].user }}
        </a>
      </li>
    {% endif %}
  {% endfor %}
</ul>
````

My code might need more logic checking & such;

Comments appreciated.
