### ISSUE TITLE
[Question] Multiple authors config

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#367]
Hi Dean,
what do you think about extending the authors feature ?

### Current state
It's possible to define one author and his details in the `config.yml`.

### Possible Change
Extend the author config to work with more data (avatar link, name, description ... ) and multiple authors

### How could this be done?
- Either stick with one author in the config.yml
- Using another file like `authors.yml` and define the data there :dagger: 
- Pickup the author in the front matter section
- author details could be displayed in a post footer

### Surplus
- beatuiful-jekyll could easily be used for sites with multiple contributors.
- This feature should be optional

**Comment by daattali** [comment]
I'm not sure if you mean: 
a) multiple authors for a single post, or
b) just supporting having a different author for different posts, or
c) multiple authors in the footer of the page

Case b) is something that several people have asked me about and I would happily support (it's already very easy to do it). Which one do you mean?

**Comment by OCram85** [comment]
Hi Dean,

I tried to explain scenario b. 😃

**Comment by daattali** [comment]
In that case, one very simple option is to just support an author param in a page YAML, without a need to change the config or to add another file. Do you think a more complex solution is needed?

**Comment by OCram85** [comment]
You're right. simple yaml definition in the front matter part should do it. Maybe an additional global setup if you simple want to select the author in the page's yaml part like this:

#### Example page / post

```` YAML
author: "OCram85"
````

#### `_config.yml`

````YAML
authors:
  OCram85:
    name: "OCram85"
    avatar: "/path/to/image.jpg"
    additional_params: ""
  daattali:
    name: "Dean"
    avatar: "/path/to/image2.jpg"
    additional_params: ""
````
