### ISSUE TITLE
Add custom social network link

### ISSUE THREAD

**Issue by zhan-gao** [daattali/beautiful-jekyll#373]
Hi, thanks very much for the amazing project.

I tried to add custom social network link in the footer by adding the following chunck of code
```
researchgate:
  name: "ResearchGate"
  baseURL: "https://www.researchgate.net/profile/"
  icon: "fa-researchgate"
```
into `SocialNetwork.yml` and invoke the link in _config.yml. I already checked the code for the icon on the fontawesome website. However, the icon of researchgate does not display succesfully. 

I would appreciate a lot if anyone can help me out. Thanks.
