### ISSUE TITLE
Support multi-level  navbar

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#43]
See if there's an elegant simple way to support dropdown menus in the navbar links.  Only if it's easy to use from the user's perspective and involves minimal code change, and make sure it looks good on both mobile and big screen.

**Comment by daattali** [comment]
Idea: for any menu item that's a dropdown, automatically place an arrow beside it by adding `:after { content: " \25BC"; }` to the text

**Comment by daattali** [comment]
done

**Comment by facelesspanda** [comment]
Thanks, but since there's no real documentation on the config specs it's hard to know how to format a nested list.

Here's the default menu you gave, that works:
```yaml
navbar-links:
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
```

Here's two attempts at nested menus that don't work:
```yaml
navbar-links:
  Cthulhu:
    Characters:
      - Edward: "edward"   # produces text ` {"Edward"=>"edward"} ` with url: ` / `
```
```yaml
navbar-links:
  Cthulhu:
    - Characters:
      - Edward: "edward"  # produces text ` "edward"}">Characters ` with url: ` /{ `
```
both create a single link under the `Cthulhu` menu, with weird text and urls.

knowing that `About Me: "aboutme"` links properly to the `aboutme.md` file, I thought `Edward:"edward"` would do so with `edward.md`, and at the nav root it does.

So what is the exact way to set up multi-level navigation?
