### ISSUE TITLE
SocialNetworks.yml: add pluspora without font awsome icon?

### ISSUE THREAD

**Issue by LupusE** [daattali/beautiful-jekyll#488]
Hi Beautiful-Jekyll Team,

I'd like to add pluspora to **_data/SocialNetworks.yml**. You've already done such great work, that it is easy to Implement ... But wait, the Icon is missing.
A quick search at [fontawsome](https://fontawesome.com/icons?d=gallery&q=pluspora), and it shows: Nothing. Also the 'asterisk' or 'star' Icons are not suitable.

I've already found https://pod.geraspora.de/posts/41a5c9f0281c0137cfc3005056264835
That describes the vanity url as
**_data/SocialNetworks.yml**
```
pluspora:
  name: "pluspora"
  baseURL: "https://www.pluspora.com/u/"
  icon: "fa-pluspora"
```

**_config.yml**
```
social-network-links:
  pluspora: lupuse
```

Until my 'Icon request' will hopefully be approved by the fontawsome team, is there a way to add an own icon?

**Comment by LupusE** [comment]
Okay, not necessary. The icon is called [diaspora](https://fontawesome.com/icons/diaspora?style=brands)

```
pluspora:
  name: "pluspora"
  baseURL: "https://www.pluspora.com/u/"
  icon: "fa-diaspora"
```
