### ISSUE TITLE
Use sensible default values for any value that's read from the config file

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#600]
As @skalee mentioned [here](https://github.com/daattali/beautiful-jekyll/pull/590#issuecomment-606386028) , when using remote themes, the user's config file will be empty and not match beautiful-jekyll's config. We need to make sure the theme still works properly even all config values are missing, perhaps by using [default values](https://shopify.github.io/liquid/filters/default/)

**Comment by skalee** [comment]
There are only about 20 references to these variables in `css/main.css`, so I agree that providing a default value every time config variable is used is a sensible solution.

However, if you consider switching to SCSS, then you could leverage variables and avoid duplicating these default values. For example:

```scss
$hover-col: {{ site.hover-col | default: "#0085A1"}};

.pager li a:focus {
  color: #FFF;
  border: 1px solid $hover-col;
  background-color: $hover-col;
}
```
