### ISSUE TITLE
Include Medium in Homepage footer

### ISSUE THREAD

**Issue by ghosh-r** [daattali/beautiful-jekyll#755]
In the homepage footer, please add an option to include the links to the author's Medium profile and publication.

```yaml
# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  medium: learningdeep  # add this line, navigates to a publication
  medium: @j.doe # this navigates to a profile
```

I want to be able to share my Medium profile and publication and the Medium logo to appear on the footer and the readers to be able to reach my Medium through the link.
