### ISSUE TITLE
Code wrapping

### ISSUE THREAD

**Issue by epwalsh** [daattali/beautiful-jekyll#76]
Hi @daattali, code automatically wraps which makes it hard to read, particularly from mobile devices. I propose adding something like this to `main.css`:

```css
.highlighter-rouge  code * {
    white-space: nowrap;
}

.highlighter-rouge pre {
    overflow-x: auto;
}

.highlighter-rouge pre code {
    white-space: pre;
}
```

This would disable wrapping and allow for horizontal scrolling.

EDIT: This solution actually had some unexpected behavior from a mobile browser, so maybe not the best way to go.
