### ISSUE TITLE
responsive feature image for blog

### ISSUE THREAD

**Issue by rupeshtiwari** [daattali/beautiful-jekyll#777]
I added custom-styles.css trying to overwrite the css to show different background image. please let me know what mistake I am doing this is not working at all.

```css
@media (min-width: 1025px) {
    .big-img .intro-header {
        background-image: url(/assets/img/feature-desktop.png) !important;
    }
}
```
